[package]
name = "devcore-test"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
devcore-core = { path = "../../../shared/core" }
devcore-environment = { path = "../environment" }
devcore-execution = { path = "../../../shared/execution" }

[lints]
workspace = true
