[workspace]
members = [
    "features/installer/app",
    "features/installer/daemon",
    "features/installer/domain",
    "features/desktop/compositor",
    "features/desktop/session",
    "features/onboarding/firstboot",
    "features/onboarding/firstbootd",
    "features/onboarding/greeter",
    "features/provision/daemon",
    "features/provision/domain",
    "features/shell/app",
    "features/studio/build",
    "features/studio/environment",
    "features/studio/extensions",
    "features/studio/test",
    "features/studio/workd",
    "features/system/hardware",
    "features/system/hardwared",
    "features/system/resource-daemon",
    "features/system/update",
    "features/system/updated",
    "shared/core",
    "shared/execution",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.90"
version = "0.1.0-alpha.0"
license = "Apache-2.0 OR MIT"

[workspace.lints.rust]
unsafe_code = "deny"
missing_debug_implementations = "warn"
missing_docs = "warn"

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = "symbols"
