[package]
name = "devcore-hardwared"
description = "DevCore read-only Hardware Manager D-Bus service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
devcore-hardware = { path = "../hardware" }
zbus = { version = "=4.4.0", default-features = true, features = ["option-as-array"] }

[lints]
workspace = true
